### ISSUE TITLE
No analysis button appears in the UI.

### ISSUE THREAD

**Issue by LarsBingBong** [up9inc/mizu#1113] opened 2022-05-25 11:26 UTC
**Describe the bug**

As described on [Analysis in Mizu](https://up9.com/docs/open-source-tools/mizu/mizu-analysis) an _Analysis_ button should appear in the upper right corner of the UI/Mizu webpage. It never does so though. And yes I've waited for several minutes and tried in Edge, Google Chrome and Firefox. To no avail.

**To Reproduce**
1. Run `mizu tap -A --analysis` or `mizu tap --namespaces NAME_OF_THE_NAMESPACE --analysis`
2. Let mizu do its magic and sniff API traffic
3. wait and see that the _Analysis_ button do **NOT** appear

**Expected behavior**
That the _Analysis_ button appears in the upper right corner.

**Logs**
Uploaded to this issue. 

**Screenshots**
![image](https://user-images.githubusercontent.com/80959443/170251415-80bea467-1441-496d-96c2-b8fe23460198.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Web Browser: Edge. Chrome and Firefox

**Comment by LarsBingBong** [comment] 2022-05-25 11:27
[mizu_logs_2022_05_25__12_58_46.zip](https://github.com/up9inc/mizu/files/8770622/mizu_logs_2022_05_25__12_58_46.zip)

**Comment by gadotroee** [comment] 2022-05-26 06:37
Hi, @LarsBingBong,

Thanks for reaching out. 
This feature (analyze) is deprecated and the problem is outdated documentation. 

We will fix the documentation after your comment but it is option that should not be available so it make sense that the button is not shown.

Can you please share what did you tried to get and maybe I can point out if you can achieve that functionality?

**Comment by LarsBingBong** [comment] 2022-05-26 07:31
@gadotroee of course. Sad. What I wanted was to export the data sniffed when using mizu to do what it do. So that the data can be analyzed later. Is this possible somehow in the current version of the project?

Thank you

**Comment by gadotroee** [comment] 2022-05-26 10:05
hi @LarsBingBong , 

I think I understand your need but in mizu currently there is no option to export the data (with a built in feature)
the idea of mizu is to be a "point tool" that you are starting and it cleans up when finished. (it will also only capture MAX size (configured from the mizu config) so it will delete data when it reaches this limit. 


you might be able to create another process that gets the traffic (maybe not all of it) and then save it somewhere else (but you also need to think where is this place because it can be very big if you take a lot of data..

**Comment by gadotroee** [comment] 2022-05-26 12:45
> Hi again @gadotroee,
> 
> Makes sense. And it's not possible to upload this data to the Up9 platform either?

Correct. 
btw, all code exists in this repo and we like to get suggestions, if you have idea of a new feature - you are more than welcome to suggest it and even implement it. 
if this is gets to a stable option, it can be then added to mizu and be part of future releases.. 

Hope this information make sense and if you have more questions - fell free to reach out (here or in out [public slack channel](https://join.slack.com/t/up9/shared_invite/zt-tfjnduli-QzlR8VV4Z1w3YnPIAJfhlQ))

**Comment by LarsBingBong** [comment] 2022-05-26 13:50
It looks like the Slack invite link you have on your website is not working. I've seen this for several other projects the last 6 months. I don't know what exactly. But, I'm pretty sure that Slack changed something.
At least I'm just lead to sign-up ... and not through to join the Up9 Slack community.

I thought the `analysis` feature as a way for Up9 to get potential customers onto the platform. But, totally okay. I guess - yeah - I have to find a way to export data from Mizu via other means. E.g. add the feature to the tool.

Thanks.

**Comment by gadotroee** [comment] 2022-06-09 06:20
Hi @LarsBingBong, 

I handled the invitation and I think you are able to join our slack, if it didn't work from some reason you can try to use [this link](https://up9.com/slack) to join.

Also, we have updated the docs to not contain invalid information about analysis and I'm closing this issue.

If you want to ask anything or suggest some features, you are more than welcome (in another new issue or in slack)

**Closed by gadotroee** 2022-06-09 06:20 UTC

**Comment by gadotroee** [comment] 2022-06-09 18:17
I see you joined, are you sure it is not working for you?

**Comment by larssb** [comment] 2022-06-11 05:48
Finally worked. But, via some weird re-directions to Slack gov and what not. But, I'm there now. Thank you!
